### ISSUE TITLE
Impersonation with async tasks

### ISSUE THREAD

**Issue by mattjohnsonpint** [mattjohnsonpint/SimpleImpersonation#32]
Considering code such as:

```csharp
Item item = await Impersonation.RunAsUser(credentials, LogonType.NewCredentials, async () =>
{
    using (var context = new MyDbContext())
    {
        return await context.Items.FirstOrDefaultAsync();
    }
});
```

While this looks correct, it appears that the task sometimes runs as if not impersonated.   This is being discussed further in dotnet/corefx#24977.

I'll leave this item open for tracking, and discussion of alternatives.  In the meantime, I recommend against using impersonation with asynchronous tasks.

**Comment by mj1856** [comment]
Hmmm... Despite the discussion on the corefx issue, I can't repro this.  I've added a test at [`ImpersonationTests.Impersonate_RunAsUser_Async`](https://github.com/mj1856/SimpleImpersonation/blob/7e23f8e22e220b119ecf09d1c9bfc40c54826fce/test/SimpleImpersonation.UnitTests/ImpersonationTests.cs#L167-L208) but it passes.  😕

**Comment by Mac95** [comment]
yes, it passes. This occured on my side when leaving the ASP.NET MVC application idle for a while. First, everything works as expected. After a while the connection to SQL-Server gets dropped and after that the error comes up. The following connection to SQL-Server is **not** under the impersonated user but using the ApplicationPoolIdentity (or whatever user the AppPool is using).

**Comment by EasyMilos** [comment]
Can we confirm few things. Where this doesn't work? Full .Net Framework or .Net Core only? ASP.NET or Desktop applications? In case of ASP.NET, if I remember correctly, there are few more settings that may cause you issues.

**Comment by WadeTheFade** [comment]
I would just like to add that when I was using 2.0.1 I ran into this issue. 

I was using async methods SQL connections to execute SQL commands within the impersonation block.

Only when multiple different users were using the service at the same time did I run into the log showing others connecting to SQL connections using other people's impersonated threads.

Had to put comments to not use async anywhere in the impersonation block. Tried all things mentioned in Readme and threads (flaw in the ointment, etc). 

I am doing a rewrite of my service now, and am upgrading to 3.0 and it looks like the issue is still around... after reading  dotnet/corefx#24977 it doesn't look like its anything within this library, but the underlying nature of Impersonation.

**Comment by avivanoff** [comment]
This might be related:  [https://github.com/aspnet/AspNetWebStack/issues/260](url).

**Comment by mattjohnsonpint** [comment]
I hadn't noticed until now, but looks like we got [`WindowsIdentity.RunImpersonatedAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonatedasync) with .NET 5.0.

I'll work on an update that targets .NET 5+ to address this issue and use the new API.

**Comment by mattjohnsonpint** [comment]
Turns out that `RunImpersonatedAsync` is just an overload for `RunImpersonated` that imposes a `Task` or `Task<T>` action.  The underlying issue was resolved some time ago using `AsyncLocal` under the hood.  No need for a separate Async API here.
